# Generated by Django 3.2 on 2021-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20210411_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loan4',
            field=models.IntegerField(max_length=1, null=True),
        ),
    ]
