# Generated by Django 3.2 on 2021-04-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_item_loan4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='loan4',
            field=models.IntegerField(null=True),
        ),
    ]
