# Generated by Django 3.2 on 2021-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_alter_item_loan4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='applyWeekend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='compWeb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='highlimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='loan4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='murisoku',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='noneCheck',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='raitenhuyou',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='shufu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='sokujitu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='syunyuusyoumei',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='teirate',
            field=models.IntegerField(default=0),
        ),
    ]
