# Generated by Django 3.2 on 2021-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kariretaImages2_32050',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='kariretaImages2_250250',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
