# Generated by Django 3.2 on 2021-04-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20210413_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='item',
            new_name='item_id',
        ),
    ]
