# Generated by Django 3.2 on 2021-04-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_rename_item_article_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='text',
        ),
    ]
