# Generated by Django 3.2 on 2021-04-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20210413_2311'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='loan',
        ),
    ]
