# Generated by Django 3.2 on 2021-04-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_alter_item_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kariretaLinkurl',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
